@startuml

title Use Case Diagram - MOVIESYS 

left to right direction


' Styling:
' !$BASEPATH = "../.."
' !include $BASEPATH/globals/stylesheet-mimeograph.iuml
' !include $BASEPATH/globals/stylesheet-sunlust.iuml


' The use case diagram must contain all use cases at the level of elementary business processes (EBP).
' The names of each use case must clearly reflect its goal and scope. You may use comments to do this if required.
' Do not forget to draw the system boundary and include all actors.


' Goals:
package "MOVIESYS" as moviesys {
    ' Goals Stuent 
    usecase "reserve tickets" as GRT
    usecase "buy tickets" as GBT
    usecase "search movies" as GSM

    usecase "manage locations" as GM1
    usecase "manage halls" as GM2
    usecase "manage movies" as GM3
    usecase "manage movie screenings" as GM4

}

rectangle "<<actor>> \n **box office**" as box
' rectangle "<<actor>> \n **online**" as online


' Actors
:moviegoer:
:administrator:



' Connections 
moviegoer -- GRT
moviegoer -- GBT
moviegoer -- GSM

administrator -- GM1
administrator -- GM2
administrator -- GM3
administrator -- GM4

GRT -- box
' GRT -- online

' ------------------------------------
' Texte 


header
' Jasmin Fässler 2026
endheader

@enduml