@startuml

title Vetragstypen 

left to right direction
skinparam linetype ortho

' ' Styling:
' !$BASEPATH = "./"
' !include $BASEPATH/globals/stylesheet-mimeograph.iuml
' !include $BASEPATH/globals/stylesheet-sunlust.iuml
' !include $BASEPATH/globals/stylesheet-jasmin.iuml

skinparam linetype ortho

' ------------------------------------

rectangle "Vertragstypen" as root

rectangle "Veräusserungsverträge" as v1
rectangle "Gebrauchsüberlassungsverträge" as v2
rectangle "Verträge auf Arbeitsleistung" as v3
rectangle "Weitere Verträge" as v4

root --> v1
root --> v2
root --> v3
root --> v4

' rechte Seite
rectangle "Kaufvertrag\n(Art. 184 ff. OR)" as k
rectangle "Tausch\n(Art. 237 f. OR)" as t
rectangle "Schenkung\n(Art. 239 ff. OR)" as s

v1 --> k
v1 --> t
v1 --> s

rectangle "Miete\n(Art. 253 ff. OR)" as m
rectangle "Pacht\n(Art. 275 ff. OR)" as p
rectangle "Gebrauchsleihe\n(Art. 305 ff. OR)" as g
rectangle "Darlehen\n(Art. 312 ff. OR)" as d
rectangle "Leasing (z. T. im Konsumkreditgesetz KKG)" as l

v2 --> m
v2 --> p
v2 --> g
v2 --> d
v2 --> l

rectangle "Arbeitsvertrag\n(Art. 319 ff. OR)" as av
rectangle "Werkvertrag\n(Art. 363 ff. OR)" as wv
rectangle "Auftrag\n(Art. 394 ff. OR)" as au

v3 --> av
v3 --> wv
v3 --> au

rectangle "Innominatverträge" as inn
v4 --> inn

@enduml

' ------------------------------------
' Texte 


header
' Jasmin Fässler 2026
endheader

@enduml